// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import Notification from 'stimulus-notification'
import TextareaAutogrow from 'stimulus-textarea-autogrow'

import HelloController from "./hello_controller"
application.register("hello", HelloController)
application.register('notification', Notification)
application.register('textarea-autogrow', TextareaAutogrow)

